POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Best sofas (and other furniture) to sharpen your claws on",
    "author": "Pök Riiviö Ollikainen",
    "url": "www.bestsofastocratch.com",
    "user": "61f822c8fed7b12aa92b5493",
    "likes": 2
}