POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxZjgyMmM4ZmVkN2IxMmFhOTJiNTQ5MyIsImlhdCI6MTY0MzcyODk5Nn0.STNc6Sm0ego1U7ZoQe4j3e_HF-oPgERYcY5nRbaMF28

{
    "title": "Best sofas (and other furniture) to sharpen your claws on",
    "author": "Pök Riiviö Ollikainen",
    "url": "www.bestsofastocratch.com",
    "user": "61f822c8fed7b12aa92b5493",
    "likes": 2
}